### ISSUE TITLE
想加个switch开关,在按钮队列上面,能加吗？

### ISSUE THREAD

**Issue by 12343954** [HJaycee/JCAlertView#10]
想加个switch开关,在按钮队列上面,能加吗？

现实业务，有开关选项，能做到吗？

谢谢

**Comment by HJaycee** [comment]
UIView *customView = [[UIView alloc] initWithFrame:CGRectMake(0, 0, 200, 150)];
JCAlertView *customAlert = [[JCAlertView alloc] initWithCustomView:customView dismissWhenTouchedBackground:YES];
[customAlert show];
用这个方法可以，确定取消按钮也需要你自己加上去

**Comment by 12343954** [comment]
谢谢，呵呵，菜鸟一个
不过要完全实现一个customview，那就没必要用了，但愿能支持一下其他组件插入功能，就好了

**Comment by HJaycee** [comment]
好

**Comment by 12343954** [comment]
重写了控件，加了个subview属性，呵呵，借花献佛吧

**Comment by 12343954** [comment]
重写了控件，加了个subview属性，呵呵，照猫画虎吧

**Comment by 12343954** [comment]
http://m.koooke.com/upload/APP/893852319267079810.jpg
![http://m.koooke.com/upload/APP/893852319267079810.jpg]

**Comment by 12343954** [comment]
![Image ](http://m.koooke.com/upload/APP/893852319267079810.jpg)

**Comment by 12343954** [comment]
![Image ](http://m.koooke.com/upload/APP/893852319267079810.jpg)

**Comment by 12343954** [comment]
搞定
![Image of ](http://m.koooke.com/upload/APP/89385231926707981.jpg)

**Comment by HJaycee** [comment]
挺不错的！

**Comment by 12343954** [comment]
呵呵，还是多亏你的代码，我想重载你的方法，结果OC里没有重载一说，唉，OC头疼
