### ISSUE TITLE
在IOS9,swift2.1中 使用JCAlertView 弹出的AlertView没有按钮

### ISSUE THREAD

**Issue by sunxiang0918** [HJaycee/JCAlertView#2]
我使用Link的方式 在swift中可以使用JCAlertView.但是调用 showOneButtonWithTitle(title: String!, message: String!, buttonType: JCAlertViewButtonType, buttonTitle: String!, click: clickHandle!) 方法.弹出的Alert框没有按钮.只有title和message.

**Comment by HJaycee** [comment]
不好意思，我还没学swift不太清楚。。。

**Comment by sunxiang0918** [comment]
找到原因了, 是由于从cocoaPods下载的JCAlertView中没有JCAlertView.bundle这个.
我手动的从你的源码中下载下来 增加到项目中(需要拖动到我的项目作为target,而不是拖动到JCAlertView这个target中.否则还是找不到).然后就能正确的显示按钮了.

**Comment by HJaycee** [comment]
解决了就好！可能是因为在pods里面JCAlertView.bundle被自动放在Resources文件夹的原因吧

**Comment by sunxiang0918** [comment]
恩恩, 反正从pods里面下载的 就只有一个 .h和.m文件. 
手动的加上就对了.

**Comment by mrr1vfe** [comment]
正解 很关键

**Comment by HJaycee** [comment]
我试了下，有按钮的，按钮的图片在JCAlertView.bundle里，你应该是这个文件没有了

**Comment by mrr1vfe** [comment]
对对对 所以我说正解么～
2016年4月4日 21:16，HJaycee <notifications@github.com>写道：我试了下，有按钮的，按钮的图片在JCAlertView.bundle里，你应该是这个文件没有了
